#!/bin/sh
# Start up
case "$1" in
"start")

su toplink /toplink/Scripts/start_Supervision
  ;;

# Shut down
"stop")
/toplink/Scripts/stop_Supervision
  ;;
*)
  echo "Usage: $0 {start|stop}"
  exit 1
esac
exit 0

